//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlabIt.Guardians.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlabIt.Guardians.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of argument &apos;{0}&apos; cannot be null..
        /// </summary>
        public static string Exception_ArgumentNullMessageWithParamName {
            get {
                return ResourceManager.GetString("Exception_ArgumentNullMessageWithParamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of argument &apos;{0}&apos; of type &apos;{1}&apos; cannot be empty..
        /// </summary>
        public static string Exception_ArgumentOfTypeXEmptyMessageWithParamName {
            get {
                return ResourceManager.GetString("Exception_ArgumentOfTypeXEmptyMessageWithParamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of argument &apos;{0}&apos; of type &apos;{1}&apos; is required to be larger than &apos;{2}&apos; but was &apos;{3}&apos;..
        /// </summary>
        public static string Exception_ArgumentOfTypeXLargerThanMessageWithParamName {
            get {
                return ResourceManager.GetString("Exception_ArgumentOfTypeXLargerThanMessageWithParamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of argument &apos;{0}&apos; of type &apos;{1}&apos; consists only of white-space characters..
        /// </summary>
        public static string Exception_ArgumentOfTypeXOnlyWhitespaceMessageWithParamName {
            get {
                return ResourceManager.GetString("Exception_ArgumentOfTypeXOnlyWhitespaceMessageWithParamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of argument &apos;{0}&apos; of type &apos;{1}&apos; is required to be shorter than &apos;{2}&apos; but was &apos;{3}&apos;..
        /// </summary>
        public static string Exception_ArgumentOfTypeXShorterThanMessageWithParamName {
            get {
                return ResourceManager.GetString("Exception_ArgumentOfTypeXShorterThanMessageWithParamName", resourceCulture);
            }
        }
    }
}
