//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlabIt.Guardians.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlabIt.Guardians.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected custom exceptions to follow naming convention by ending with &apos;{0}&apos;..
        /// </summary>
        internal static string Test_ExpectedCustomExceptionsToFollowNamingConvention {
            get {
                return ResourceManager.GetString("Test_ExpectedCustomExceptionsToFollowNamingConvention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected the invalid input data to cause an exception of type &apos;{0}&apos;..
        /// </summary>
        internal static string Test_ExpectedExceptionOfTypeXBecauseInvalidInput {
            get {
                return ResourceManager.GetString("Test_ExpectedExceptionOfTypeXBecauseInvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected exception of type &apos;{0}&apos; to be serialized and deserialized correctly..
        /// </summary>
        internal static string Test_ExpectedExceptionOfTypeXToBeSerializedAndDeserializedCorrectly {
            get {
                return ResourceManager.GetString("Test_ExpectedExceptionOfTypeXToBeSerializedAndDeserializedCorrectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected the parameter name of the input argument to match the parameter name from the resulting exception..
        /// </summary>
        internal static string Test_ExpectedInputParameterNameToMatchExceptionParameterName {
            get {
                return ResourceManager.GetString("Test_ExpectedInputParameterNameToMatchExceptionParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected the given message to match the message from the resulting exception..
        /// </summary>
        internal static string Test_ExpectedMessageToMatchExceptionMessage {
            get {
                return ResourceManager.GetString("Test_ExpectedMessageToMatchExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected the valid input data to not cause any exception..
        /// </summary>
        internal static string Test_ExpectedNoExceptionBecauseValidInput {
            get {
                return ResourceManager.GetString("Test_ExpectedNoExceptionBecauseValidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected output to be equal to the input..
        /// </summary>
        internal static string Test_ExpectedOutputIsEqualToInput {
            get {
                return ResourceManager.GetString("Test_ExpectedOutputIsEqualToInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected output reference to be same object reference as input..
        /// </summary>
        internal static string Test_ExpectedOutputIsReferenceEqualToInput {
            get {
                return ResourceManager.GetString("Test_ExpectedOutputIsReferenceEqualToInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected property &apos;{0}&apos; to be not set..
        /// </summary>
        internal static string Test_ExpectedPropertyToBeNotSet {
            get {
                return ResourceManager.GetString("Test_ExpectedPropertyToBeNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected property &apos;{0}&apos; to be set..
        /// </summary>
        internal static string Test_ExpectedPropertyToBeSet {
            get {
                return ResourceManager.GetString("Test_ExpectedPropertyToBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected property &apos;{0}&apos; to match the expected value &apos;{1}&apos;, but was &apos;{2}&apos;..
        /// </summary>
        internal static string Test_ExpectedPropertyToMatch {
            get {
                return ResourceManager.GetString("Test_ExpectedPropertyToMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected type &apos;{0}&apos; to be marked with attribute of type &apos;{1}&apos;..
        /// </summary>
        internal static string Test_ExpectedTypeToBeMarkedWithAttributeOfType {
            get {
                return ResourceManager.GetString("Test_ExpectedTypeToBeMarkedWithAttributeOfType", resourceCulture);
            }
        }
    }
}
