name: "Continuous Integration"

on:
  push:
    branches-ignore:
      - master

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  BUILD_CONFIGURATION: "Release"
  TEST_RESULTS_DIR: "./test-results/"
  RUN_BENCHMARK: "false"
  COMPRESS_ARTIFACTS: "true"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Avoid shallow clone so NBGV can do its work.

      # Use Nerdbank.GitVersioning to set version variables: https://github.com/AArnott/nbgv
      - name: Set version
        uses: aarnott/nbgv@master
        with:
          setAllVars: true

      - name: Run dotnet pipeline
        uses: addnab/docker-run-action@v3
        with:
          image: flabit/dotnet-pipeline:latest
          options: -v ${{ github.workspace }}:/build/source -e SOLUTION_FILE=./FlabIt.Guardians.sln -e CONFIGURATION=${{ env.BUILD_CONFIGURATION }} -e FRAMEWORK=net6.0 -e COMPRESS_ARTIFACTS=${{ env.COMPRESS_ARTIFACTS }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v1
        with:
          name: FlabIt.Guardians v${{ env.NBGV_AssemblyInformationalVersion }}
          path: "./artifacts.zip"

      - name: Code Coverage reports
        uses: actions/upload-artifact@v1
        with:
          name: Coverage Report v${{ env.NBGV_AssemblyInformationalVersion }}
          path: "./coverage-reports.zip"

      - name: Benchmark reports
        uses: actions/upload-artifact@v1
        if: env.RUN_BENCHMARK == 'true'
        with:
          name: Benchmark Report v${{ env.NBGV_AssemblyInformationalVersion }}
          path: "./benchmark-reports.zip"
