name: "Update NuGet Packages"

on:
  schedule:
    - cron:  '0 0 * * 3'

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.412'

    - name: Update NuGet Packages
      run: ./.build/update_nuget_packages.ps1 -repository_name "${{ github.REPOSITORY }}" -github_token "${{ secrets.NUKEEPER_PIPELINE_TOKEN }}" -exclude "Microsoft.CodeCoverage"
      shell: pwsh
